### ISSUE TITLE
[VSCode] Cannot provide a main script to run in launch configurations

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-lang#10661]
**Description:**
For the `launch.json` we `"script": "${file}"` element as the script path.

```yaml
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "ballerina",
            "request": "launch",
            "name": "Ballerina Debug",
            "script": "${file}"
        },
        {
            "type": "ballerina",
            "request": "attach",
            "name": "Ballerina Remote Debug",
            "host": "127.0.0.1",
            "port": 5000
        }
    ]
}
```
Most of the time when we are in **wrong script**(that doesn't have a main function) or when we are in a **other file**(such as launch.json); VSCode **Debug** fails with following errors;

```bash
error: cannot find package '.vscode'
error: cannot find package '.ballerina'
```
