### ISSUE TITLE
Template support in add command

### ISSUE THREAD

**Issue by hevayo** [ballerina-platform/ballerina-lang#17855]
**Description:**
A template is used by ballerina add command to create a new module. You can define your custom template and share through Ballerina central. A module template is a Ballerina module that we tag as a template.

To create a new template do the following
You need to create a Ballerina project. 
Create a new module and include template files.
In Ballerina.toml specify the module as a template.
```toml
[project]
orgName= "wso2"
version= "1.1.0"
templates= ["aggregator", <module-name>]
```
Once you complete the template you can build and push to central.

To use the template
Pull the template from central 
$ ballerina pull wso2/aggregator
Then use it with the add command
`$ ballerina add myAggregator -t wso2/aggregator`   <- default to latest version
`$ ballerina add myAggregator -t wso2/aggregator:1.2.3`
