### ISSUE TITLE
When JDBC drivrer is added as a dependency in toml, it gets packed but still driver is not found when running

### ISSUE THREAD

**Issue by Manuri** [ballerina-platform/ballerina-lang#18009]
**Description:**
$Subject. Please note that, this happens only when running with `ballerina` command. Works as expected when running with `java` command

Sample toml file:
```toml
[project]
org-name= "manurip"
version= "0.1.0"

[platform]
target = "java"

    [[platform.libraries]]
    artafactId = "mysql-connector-java"
    version = "8.0.17"
    path = "/path/to/mysql-connector-java-8.0.17.jar"
    groupId = "mysql"
    modules = ["mymod"]
```

Following is the content of the created executable jar. This contains the mysql classes. The issue could be due to some resources not being included as expected.

[output.txt](https://github.com/ballerina-platform/ballerina-lang/files/3564549/output.txt)

Following is the project this issue occurred with.

[dependencyTestProject.zip](https://github.com/ballerina-platform/ballerina-lang/files/3564555/dependencyTestProject.zip)

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**
