### ISSUE TITLE
Dependency jars in the module not getting packed when imported by another module in the same project

### ISSUE THREAD

**Issue by Manuri** [ballerina-platform/ballerina-lang#18998]
**Description:**
Module structure

```bash
├── Ballerina.toml
├── dependencyIssue.iml
├── lib
│   └── mysql-connector-java-8.0.17.jar
├── src
│   ├── mod1
│   │   ├── Module.md
│   │   ├── main.bal
│   │   ├── resources
│   │   └── tests
│   │       ├── main_test.bal
│   │       └── resources
│   └── mod2
│       ├── Module.md
│       ├── main.bal
│       ├── resources
│       └── tests
│           ├── main_test.bal
│           └── resources
└── tests
    └── resources
```

mod2 imports mod1. mod1 has a dependency on a jar.
Toml content:

```toml
[project]
org-name = "myorg"
version = "0.1.0"
[dependencies]

[platform]
target = "java8"

    [[platform.libraries]]
    artafactId = "mysql-connector-java"
    version = "8.0.17"
    path = "lib/mysql-connector-java-8.0.17.jar"
    groupId = "mysql"
    modules = ["mod1"]
```

When build with,
```bash
ballerina build -a
```

It fails with following logs:

```bash
Compiling source
        myorg/mod2:0.1.0
        myorg/mod1:0.1.0

Creating balos
        target/balo/mod2-2019r3-any-0.1.0.balo
        target/balo/mod1-2019r3-java8-0.1.0.balo
error: unable to copy native jar: /Users/manurip/MyDocuments/WORK/RnD/Ballerina/100-rc1-testing/dependencyIssue/target/tmp/mysql-connector-java-8.0.17.jar
```

But once I change the toml as follows,
```toml
[project]
org-name = "myorg"
version = "0.1.0"
[dependencies]

[platform]
target = "java8"

    [[platform.libraries]]
    artafactId = "mysql-connector-java"
    version = "8.0.17"
    path = "lib/mysql-connector-java-8.0.17.jar"
    groupId = "mysql"
    modules = ["mod2"] # <---- changed mod1 -> mod2
```
Build is sucessful and dependency jar gets packed as expected.

```bash
Compiling source
        myorg/mod2:0.1.0
        myorg/mod1:0.1.0

Creating balos
        target/balo/mod2-2019r3-java8-0.1.0.balo
        target/balo/mod1-2019r3-any-0.1.0.balo

Running tests
    myorg/mod1:0.1.0
I'm the before suite function!
I'm the before function!
I'm in test function!
I'm the after function!
I'm the after suite function!
        1 passing
        0 failing
        0 skipped
    myorg/mod2:0.1.0
I'm the before suite function!
I'm the before function!
I'm in test function!
I'm the after function!
I'm the after suite function!
        1 passing
        0 failing
        0 skipped

Generating executables
        target/bin/mod2.jar

```

**Steps to reproduce:**

**Affected Versions:**
1.0.0
[dependencyIssue.zip](https://github.com/ballerina-platform/ballerina-lang/files/3599165/dependencyIssue.zip)
