### ISSUE TITLE
JDBC driver not found when running jar file directly

### ISSUE THREAD

**Issue by RobRMackay** [ballerina-platform/ballerina-lang#19625]
**Description:**
When running the code directly using Ballerina run <modulename> it executes, finds the jdbc driver jar, connects to the database and everything is happy.

When running the jar file either with "ballerina run target/bin/module.jar" it does not find the jdbc jar file, alternately running "java -jar target/bin/module.jar" both fail with 

error: {ballerinax/java.jdbc}ApplicationError message=error in sql connector configuration: Failed to get driver instance for jdbcUrl=jdbc:postgresql://postgres:5432/postgres:No suitable driver

**Steps to reproduce:**
import ballerinax/java.jdbc;

jdbc:Client dbClient = new({
url: dbUrl, username: username, password: password, 
poolOptions: { maximumPoolSize: poolsize }
}
);

have tried -cp, -classpath, env CLASSPATH, placing the driver in the distribution/bre/lib folder ( this works for the cli run command) or by placing the jar in the same directory as the module jar.

**Affected Versions:**
Ballerina 1.0.1
Language specification 2019R3

**OS, DB, other environment details and versions:**
Mac and Linux, postgres and mysql
**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Manuri** [comment]
I suppose you might not have added the driver dependency to the `Ballerina.toml` like below. Could you please check?

```toml
[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "msql-connector-java"
    version = "1.0.0"
    path = "/path/to/driver"
    groupId = "mysql"
    modules = ["mymodule"]
```
