### ISSUE TITLE
BBE:  Creating docker image in OpenShift Deployment

### ISSUE THREAD

**Issue by parkavi11** [ballerina-platform/ballerina-lang#20434]
**Description:**
When following the steps in BBE (https://ballerina.io/learn/by-example/openshift-deployment.html), I cannot trigger a build to create the Docker image since the generated ./kubernetes/openshift/openshift_deployment.yaml file has some errors. 

Here is the modified .yaml file to make the push successful. 
```
---
apiVersion: "v1"
kind: "BuildConfig"
metadata:
  annotations: {}
  labels:
    build: "openshift-openshift-bc-openshift-bc"
  name: "openshift-openshift-bc-openshift-bc"
  namespace: "hello-api"
spec:
  nodeSelector: {}
  output:
    to:
      kind: "ImageStreamTag"
      name: "hello-service:v1.0"
  source:
    binary: {}
  strategy:
    dockerStrategy:
      dockerfilePath: "docker/Dockerfile"
      forcePull: false
      noCache: false
  triggers: []
---
apiVersion: "v1"
kind: "ImageStream"
metadata:
  annotations: {}
  labels:
    build: "openshift-openshift-bc-openshift-bc"
  name: "hello-service"
  namespace: "hello-api"
```

**Steps to reproduce:**
After deploying the artifacts, when 
``` oc start-build bc/openshift-openshift-bc-openshift-bc --from-dir=. --follow ```

**Affected Versions:**
1.1.0-alpha

**Suggested Labels (optional):**
Area/BuildTools, Type/Bug
