### ISSUE TITLE
`ballerina build` command reads ballerina.conf in the same directory

### ISSUE THREAD

**Issue by a5anka** [ballerina-platform/ballerina-lang#20777]
## Description

This happens when you have a ballerina.conf file in the same directory path where you execute `ballerina build`. 
 
## Steps to reproduce

- Add a `ballerina.conf` file with the following content in the directory where the `ballerina build` command is executed.
   ```toml
   [b7a.observability.tracing]
   enabled=true
   name="foo"
   ```

- You should see the following error in the build output.
  ```
  error: observability enabled but no tracing extension found for name foo
  ```

## Affected Versions

1.1.0

## Related Issues (optional)

#20362
