### ISSUE TITLE
Change the return type of getAsMap() to map<anydata>

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#21707]
In the config API, the current return type of the `getAsMap()` function is `map<any>`. Need to make the return type `map<anydata>`. Otherwise it makes it difficult to use `getAsMap()` in conjunction with other functions in the API (e.g., `getAsArray()` which returns `anydata`). Instead of working with `anydata`, you have to work with `any`, as in the example below.
```ballerina
import ballerina/config;
import ballerina/io;

public function main() {
	any[] cnf = config:getAsArray("jwtTokenConfig");
	map<any> m = <map<any>>cnf[0];
	map<any> claims = <map<any>>m["claims"];
	io:println(claims);
}
```
The sample conf file:
```toml
[[jwtTokenConfig]]
 issuer = "https://localhost:9443/oauth2/token"
 audience = "http://org.wso2.apimgt/gateway"
 certificateAlias = "wso2apim310"
 validateSubscription = false
 [jwtTokenConfig.claims]
   scope="scps"
   iss="isss"

[[jwtTokenConfig]]
 issuer = "https://localhost:9443/oauth2/token"
 audience = "http://org.wso2.apimgt/gateway"
 certificateAlias = "idptest"
 validateSubscription = false
 [jwtTokenConfig.claims]
   scope="scpsss"
   iss="isssss"
```
