### ISSUE TITLE
OpenAPI to Ballerina conversion needs to support Quoted Identifiers with special characters

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-lang#25015]
**Description:**
The current OpenAPI to Ballerina tool does not support parsing special characters. The generated outcomes have deviations from the expected bal program.

**Steps to reproduce:**
Considering quoted identifiers in ballerina, there can be 3 places where we need to support.

Case 1 : operationId -> service resource function
```yaml
...
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets resource_!$:[;  
#This should generate a function with identifier " 'listPets\ resource_\!\$\:\[\;"
      tags:
        - pets
      parameters:
       ...
      responses:
...
```
Case 2 : component -> record type objects
```yaml
...
components:
  schemas:
    Pet_sample_!$:[; : 
#This should generate a record type object with identifier " 'Pet_sample_\!\$\:\[\;"
      required:
        - sample_resource_!$:[;_id
        #The object should have a field with identifier " 'sample_resource_\!\$\:\[\;_id"
        - name
      properties:
...
```
Case 3: service name argument in command line -> service name

The following command must generate a service with identifier `'sample_service_\ \!\:\[\;` (same as the argument)

`$BAL_HOME/bin/ballerina openapi gen-service petStore:sample_service_\ \!\:\[\; hello.openapi.yaml
`

Currently the special characters are replaced with `_`

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
#18720 

**Suggested Labels (optional):**
Area/Tooling

**Suggested Assignees (optional):**
