### ISSUE TITLE
Fix ordering of boolean flag with table type in TypeWriter 

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#25926]
**Description:**
Currently, for table type in BIRTypeWriter, the order of writing boolean values for fieldNameList and keyTypeConstraint is not the same as defined in ksy file where the structure defined as below.

```yaml
  type_table:
    seq:
      - id: constraint_type_cp_index
        type: s4
      - id: has_field_name_list
        type: u1
      - id: field_name_list
        type: table_field_name_list
        if: has_field_name_list == 1
      - id: has_key_constraint_type
        type: u1
      - id : key_constraint_type_cp_index
        type: s4
        if: has_key_constraint_type == 1
```
Need to update BIRTypeWriter table type to this order defined above.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**
