### ISSUE TITLE
Incorrect error message when a JAR that is specified as a platform library dependency is unavailable

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#26225]
**Description:**
$title.  

**Steps to reproduce:**
Introduce a module `foo` in a project with https://ballerina.io/swan-lake/learn/by-example/mysql-init-options.html as the source.

In the Ballerina.toml file include

```toml
[platform]
target = "java8"

[[platform.libraries]]
path = "mysql-connector-java-8.0.18.jar"
```

When the JAR file is not available though, the following error is logged.

```cmd
$ ballerina build foo
Compiling source
        maryam/foo:0.1.0

Creating balos
error: dependency jar not found : org.ballerinalang.toml.model.Library@2a1debfa
```

**Affected Versions:**
slp4
