### ISSUE TITLE
 [Configurable] Improve configuration support for other types

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-lang#27131]
**Description:**
Currently we support only `int`, `float`,`boolean` and `string` type variables as configurables. We need to support the other types as well.

Further related improvements - 
 - support optional organization name in TOML
> The organization name would only be required when necessary to resolve an ambiguity.
 - support toml key-value specification for directly specify module & variable name
   Eg. : 
```toml
[moduleName.subModuleName]
variable1 = 11
variable2 = "abc"
```
This should be equivalent to the following as well. 
```toml
moduleName.subModuleName.variable1 = 11
moduleName.subModuleName.variable2 = "abc"

```
**Steps to reproduce:**

**Affected Versions:**
SLP6

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**
Team/jBallerina, Language/Configurable

**Suggested Assignees (optional):**
