### ISSUE TITLE
Need to support literal string values in TOML parser

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-lang#27378]
**Description:**
$subject

As the TOML parser will be used for `configurable` variables, It's good to support TOML literal strings that can include special characters witth no escaping. 

Eg. - 
```toml
path = '\\ServerX\admin$\system32\'
regexKey = '''I [dw]on't need \d{2} apples'''
```

referred :[https://toml.io/en/v0.4.0#string]( https://toml.io/en/v0.4.0#string)

**Steps to reproduce:**

**Affected Versions:**
slp7

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
#27129 

**Suggested Labels (optional):**
Team/DevTools, Area/TOMLParser

**Suggested Assignees (optional):**
