### ISSUE TITLE
TOML Parser returns wrong nodes for dotted TOML keys

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-lang#27789]
**Description:**
$subject

**Steps to reproduce:**
The following TOML table and the key-value pairs must be returning similar table nodes when parsing. 
```toml
[abc.main]
intKey = 42
floatKey = 3.5
stringKey = "x" 

abc.main.intKey = 42
abc.main.floatKey = 3.5
abc.main.stringKey = "x" 
```
The resulting node of the table is 
```
TOML table - abc 
           | --- TOML table - main
                            | --- TOML Key-Value - "intKey" = 42                              
                            | --- TOML Key-Value - "floatKey" = 3.5  
                            | --- TOML Key-Value - "stringKey" = "x" 

```
And the resulting node of the dotted keys are 
``` 
TOML table - abc 
           | --- TOML table - main
                            | --- TOML Key-Value - "intKey" = 42    
TOML table - main 
           | --- TOML Key-Value - "floatKey" = 3.5    
TOML Key-Value - "stringKey" = "x" 
``` 

**Affected Versions:**
slp9-SNAPSHOT

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
#27431 

**Suggested Labels (optional):**

**Suggested Assignees (optional):**
