### ISSUE TITLE
Platform dependencies not considering to decide platform of the package

### ISSUE THREAD

**Issue by pramodya1994** [ballerina-platform/ballerina-lang#28142]
**Description:**
Currently, the direct dependencies of imports in the package are deciding the platform of the package.
If those direct dependencies have any `ballerina/java` dependency platform of the package will be taken as `java11`. Else platform will be `any`.

But when a package has a platform dependency with platform `java11` like below, it is not taken in to consideration to decide the platform of the package and thus set as **_any_**. 
```toml
[[platform.java11.dependency]]
path = "/user/sameera/libs/toml4j.jar"
artifactId = "toml4j"
version = "0.7.2"
groupId = "com.moandjiezana.toml"
```

Since `[[platform.java11.dependency]]` in `Ballerina.toml` requires `java11` for execution and so we need to consider this entry when we are deciding the platform.

Adding this issue to discuss this matter.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**
