### ISSUE TITLE
Improve configurable error messages thrown at value creation

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-lang#28812]
**Description:**
$subject

**Steps to reproduce:**
```ballerina
type Module record {
 readonly string name;
 string level;
};
final configurable table<Module> key(name) & readonly modules = table [];
```

Config.toml
```toml
[[log.modules]]
name = "foo"
level = "DEBUG"
[[log.modules]]
name = "foo"
level = "ERROR"
```
Error message : 
```
error: {ballerina/lang.table}KeyConstraintViolation {"message":"A value found for key 'myorg/myproject.foo'"}
```

We need to provide more informative messages related to configurables in similar cases.

**Affected Versions:**
alpha2

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**
