### ISSUE TITLE
Toml parser diagnostics location text range differs in different platforms

### ISSUE THREAD

**Issue by pramodya1994** [ballerina-platform/ballerina-lang#29580]
**Description:**
When there is an error in a toml, toml parser diagnostics in the windows platform diagnostic location text range has incremented by 1 compared to the actual location.

This does not happen in Linux.

```
Linux:   (17,33)
Windows: (18,34)
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by xlight05** [comment]
@pramodya1994 @pubudu91 isn't this the expected behavior? 
I've ran a test using ballerina parser on windows and ubuntu. It has the same behavior.
Windows- 
![windows-textrange](https://user-images.githubusercontent.com/23274047/117786491-2d830600-b263-11eb-8930-722460b0a42f.PNG)
Ubuntu-
![ubuntu-text-range](https://user-images.githubusercontent.com/23274047/117786517-3673d780-b263-11eb-92f5-2571fed281ed.png)

**Comment by pramodya1994** [comment]
@pubudu91 It's the source we have used for the `BallerinaTomlTests.testBallerinaTomlWithInvalidOrgNameVersion` test case.
```toml
[package]
name = "winery-project"
org = "foo.one"
version = "100"
license= ["Apache 2.0"]
authors= ["jo", "pramodya"]
keywords= ["toml", "ballerina"]
repository= "https://github.com/ballerina-platform/ballerina-lang"

[[platform.java11.dependency]]
path = "../dummy-jars/toml4j.txt"
artifactId = "toml4j"
version = "0.7.2"
groupId = "com.moandjiezana.toml"

[[platform.java11.dependency]]
path = "../dummy-jars/swagger.txt"
artifactId = "swagger"
version = "0.7.2"
groupId = "swagger.io"

[build-options]
observabilityIncluded = true
offline = true
skipTests = false
```
