### ISSUE TITLE
Config.toml file throws invalid escape sequence error when running in Windows

### ISSUE THREAD

**Issue by MadhukaHarith92** [ballerina-platform/ballerina-lang#29669]
**Description:**
$Subject

**Steps to reproduce:**
1. Create a ballerina project in Windows system.
2. Add the following entry to a `Config.toml` file
```
[log]
level = "WARN"
format = "json"

[[log.modules]]
name = "myorg/myproject"
level = "DEBUG"

[[log.modules]]
name = "myorg/myproject.foo"
level = "ERROR"
```
3. Run the project.
4. Re-run with the following entry as well.
```
[integration_tests]
bal_exec_path = "@exec.path@/bal"
temp_dir_path = "@temp.path@/bal"
```

**Affected Versions:**
SLAlpha3

**OS, DB, other environment details and versions:**
Windows OS

**Comment by HindujaB** [comment]
Seems to be a bug from toml parser. @xlight05 could you have a look?

**Comment by xlight05** [comment]
I couldn't reproduce this neh,

toml file
```toml
[log]
level = "WARN"
format = "json"

[[log.modules]]
name = "myorg/myproject"
level = "DEBUG"

[[log.modules]]
name = "myorg/myproject.foo"
level = "ERROR"

[integration_tests]
bal_exec_path = "@exec.path@/bal"
temp_dir_path = "@temp.path@/bal"

```

I ran this in a windows PC. I don't get any diagnostics. ;o
