### ISSUE TITLE
Support record arrays in configurables

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-lang#29929]
**Description:**
$subject
sub task of #28976 

**Describe your task(s)**
Record arrays are similar to table of records. Therefore, it's preferred to support array of records

```ballerina
type Person record {|
    string name;     
|};

configurable Person[] & readonly recordArr = ?;

```
In  `Config.toml`
```toml
[[recordArr]]
name = "John Doe"

[[recordArr]]
name = "Jane Doe"
```

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by warunalakshitha** [comment]
How can we define an array of record of records in config.toml?

```
public type Person record {
     string name;
     int id;
     Address address;
};

public type Address record {
    int number;
    string city;
};

configurable Person[] & readonly personArr = ?;

```

**Comment by HindujaB** [comment]
I think we can add like this 
```toml
[[personArr]]
name = "John Doe"
id = 101
address.number=11
address.city="Colombo"

[[personArr]]
name = "Jane Doe"
id = 102
address.number=22
address.city="Kandy"
```
Since we support dotted keys in toml parser this will be valid
