### ISSUE TITLE
Support record of records for configurables

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-lang#29930]
**Description:**
$subject
sub task of #28976 

**Describe your task(s)**
As records can be specified as TOML tables in `Config.toml`, we need to support record fields with type record.

```ballerina
type Address record {|
    string city; 
    string country; 
|};

type Person record {|
    string name; 
    Address address;    
|};

configurable Person & readonly person = ?;

```

In  `Config.toml`
```toml
[person]
name = "John Doe"
address.city="Colombo"
address.country="Sri Lanka"
```

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**
