### ISSUE TITLE
Support toml parts coming from multiple sections

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#29996]
**Description:**
Support toml parts coming from multiple sections in to the same module. Currently only the most specific part is picked.

**Steps to reproduce:**
``` toml
intVar1 = 1 # not picked
[myRootModule]
intVar2 = 2  # picked
intVar3 = 3  # picked
```

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
introduced in #29924

**Suggested Labels (optional):**

**Suggested Assignees (optional):**
