### ISSUE TITLE
Toml validations are not working for array type tables

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-lang#30304]
**Description:**
When there is an array type table in a toml file, the validations are only applied for the first element in the array.
Found this while implementing #30221. Adding validations to the Dependencies.toml schema only works for the first entry.

Sample file used:
```toml
[[dependency]]
org = "foo"
name = "winery"
version = "0.1.0"

[[dependency]]
org = "bar"
name = "math"
version = "0.1.0"
```
