### ISSUE TITLE
Modules are not updated for Dependencies.toml edit

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-lang#30359]
**Description:**
When the Dependencies.toml is edited, the modules should be reset.

**Steps to reproduce:**
Create two versions of the same package with a signature change in a function and check diagnostics in VScode by switching the version.

1. Create a new lib package, build and push to local repo.
    $ bal new -t lib proj1
   **_proj1.bal_**
   ```bal
   import ballerina/io;

   public function hello() {
       io:println("Hello World!");
   }
   ```
   _**Ballerina.toml**_
   ```toml
    [package]
    org = "testOrg"
    name = "proj1"
    version = "0.1.0"
    ```
    
2. Edit the main.bal and the Ballerina.toml of the package as follows:
   Edit the `proj1.bal` file to add a parameter to the `hello` function
**_proj1.bal_**
   ```bal
   import ballerina/io;

   public function hello(string p1) {
       io:println("Hello World!");
   }
   ```
   Edit the Ballerina.toml to change the version
   _**Ballerina.toml**_
   ```toml
    [package]
    org = "testOrg"
    name = "proj1"
    version = "0.1.1"
    ```
3. Build and push the updated package to local repo.
4. Create a new project that uses the first package an open in VSCode
   $ bal new projTest
   _**main.bal**_
   ```bal
    import testOrg/proj1;
    
    public function main() {
        proj1:hello();
        
    }
   ``` 
    _**Dependencies.toml**_
   ```toml
    [[dependency]]
    org = "testOrg"
    name = "proj1"
    version = "0.1.0"
    ```
5. Change the version in `Dependencies.toml` to `0.1.1`

**Expected behavior:**
    Show diagnostic `missing required parameter 'p1' in call to 'hello()'`
    Go-to-def would direct to the file in version `0.1.1`

**Current behavior**
   No diagnostics shown
   Go-to-def would direct to the file in version `0.1.0`
