### ISSUE TITLE
Support map<anydata> for Configurables

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-lang#30389]
The configurable variables must support `map<anydata>` type through TOML syntax.
This issue  describes the map of constraints with a specific type. 
Eg. - 
```ballerina
type Person record {|
    int id;
    string name;
|};
configurable map<int> & readonly numbers = ?;
configurable map<string[][]> & readonly stringSet = ?;
configurable map<Person> & readonly person = ?;
```
These variables can be configured with following TOML syntax

```toml
[numbers]
one = 1
two = 2
three = 3
four = 4

[stringSet]
set1 = [["a","aa","aaa"], ["b","bb","bbb"],["c","cc","ccc"]]
set2 = [["d","dd","ddd"], ["e","ee","eee"],["f","ff","fff"]]
set3 = [["g","gg","ggg"], ["h","hh","hhh"],["i","ii","iii"]]

[person]
person1.id = 11
person1.name = "Tom"
person2.id = 22
person2.name = "John"
person3.id = 33
person3.name = "Jack"

```

In similar ways, 
we need to support 
 - `map<anydata>[]`
 - `table<map<anydata>>`
