### ISSUE TITLE
TOML parser diagnostics seems to be zero based

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#30501]
Consider the following `Ballerina.toml` file:
```toml
[package]
org = "pubudu"
name = "test"
version = "0.1.0

[build-options]
observabilityIncluded = true
```
Note the missing `"` at the end of `0.1.0`. For this, I get the following diagnostic:
```
ERROR [Ballerina.toml:(4:0,4:0)] missing double quote token
```
This should've given the position as `5, 1`.
