### ISSUE TITLE
Map iterator does not work for map<record> configurable variables from non-default module

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-lang#30566]
**Description:**
When there is a `map<record>` typed configurable variable created from an imported map type of a non-default module, 
the map iterator function gives a no record found error. 

**Steps to reproduce:**
In a package where default module name is `main` and a non-default module with name `main.mod1`,
In mod1.bal,
```ballerina
public type Student record {
    string name = "";
    int id = 1;
};
public type StudentMap map<Student>;
```
In main.bal,
```ballerina
import ballerina/io;
import main.mod1;
configurable mod1:StudentMap & readonly studentMap = ?;

public function main() {
    int count = 0;
    foreach var entry in studentMap {
        count += 1;
    }
    io:println(count);
}
```
And in `Config.toml`,
```toml
[studentMap]
student1.id = 11
student1.name = "Anne"
student2.id = 22
student2.name = "Bob"
student3.id = 33
student3.name = "Charles"
```
Error:
```
error: No such record: Student & readonly
        at ballerina.lang.map.1_1_0:externNext(internal.bal:35)
           ballerina.lang.map.1_1_0.MapIterator:next(internal.bal:31)
```
**Affected Versions:**
beta1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
#30389 

**Suggested Labels (optional):**

**Suggested Assignees (optional):**
