### ISSUE TITLE
Fix ambiguities between map type configurable variables and org/module names

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-lang#30571]
**Description:**
As mapping values are supported by `configurable` variables through the TOML syntax as follows
```toml
[orgName.moduleName.varName]
field1 = "value"
```
And the simple type variables also can be supported through the TOML syntax of TOML tables
```toml
[orgName.moduleName]
varName = "value"
```
There is a possibility of ambiguity between modules and map/record typed configurable variables. 

We need to resolve such ambiguities at compile time as per [#800](https://github.com/ballerina-platform/ballerina-spec/issues/800#issuecomment-811587356)

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**
#30389 

**Suggested Labels (optional):**

**Suggested Assignees (optional):**
