### ISSUE TITLE
Remove version of dependencies from BIR

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-lang#31173]
**Description:**
When two compatible versions for a dependency exist in the dependency graph, Project API resolves it to the latest version. During compilation, if the dependencies are resolved from the BIR from the initial run, this scenario fails at the BIR loading phase if the BIR is built with the old version of the respective dependency. 

**Affected Versions**
SL Beta1

**Comment by azinneera** [comment]
**Steps to reproduce**

The issue can be reproduced as follows with SL Beta1 distribution.

1. Create a newer compatible version of http (e.g.: `1.1.0-beta-1.1`), build and publish it to local repo using `bal push --repository=local`. Now the distribution should contain http `1.1.0-beta.1` and the local repo should have `1.1.0-beta.1.1`
2. Create a new package with `bal new` command and do the following changes:

**_main.bal_**
```bal
import ballerina/websub as _;
import ballerina/http as _;
```
**_Dependencies.toml_**
```toml
[[dependency]]
org = "ballerina"
name = "websub"
version = "1.2.0-beta.1"

[[dependency]]
org = "ballerina"
name = "http"
version = "1.1.0-beta.1.1"
repository = "local"
```

3. Now, build the project using `bal build`

**_Output:_**
```
Compiling source
	asmaj/testPkg:0.1.0
error: failed to load the module 'ballerina/websub:1.2.0-beta.1' from its BIR
```
This happens because Project API resolves to the latest http version `1.1.0-beta.1.1` whereas the BIR of the websub module is built with the http `1.1.0-beta.1` version and when loading dependencies, it looks for the symbols by the older version.
