### ISSUE TITLE
Issue on parameter generation on remote functions with a ballerina reserved keyword `From`

### ISSUE THREAD

**Issue by SkNuwanTissera** [ballerina-platform/ballerina-lang#32512]
**Description:**
The issue is on parameter generation on remote functions with a ballerina reserved keyword `From`
Refer to the code snippet from openapi.yml
```
    from_header:
      name: From
      in: header
      description: The email address of a valid user associated with the account making the request.
      required: true
      schema:
        type: string
        format: email
```
Refer to a sample remote function generated which uses the above parameters.
```
remote isolated function mergeIncidents(string accept, string contentType, string id, string from, Body20 payload)
```
This needs to appear in a form of `string 'from;`

**Steps to reproduce:**
1. Use [this](https://gist.github.com/SkNuwanTissera/4e96cb477e70f2adb86eb6b06970facd) openapi.yml to generate using [openapi tool](https://github.com/ballerina-platform/ballerina-openapi)
2. Build the code and observe for errors.
3. You will observe the below error
```
ERROR [client.bal:(2525:87,2525:88)] invalid token 'from'
ERROR [client.bal:(2527:89,2527:94)] undefined symbol 'from'
```

**Affected Versions:**

**OS, DB, other environment details and versions:**
Ballerina SL beta2
