### ISSUE TITLE
Add `visibility` to `Ballerina.toml`

### ISSUE THREAD

**Issue by pramodya1994** [ballerina-platform/ballerina-lang#33362]
**Description:**
`visibility` is used to capture whether a package is public or private within a repository.
```toml
[package]
org = "samjs"
name = "yaml"
version = "0.1.0"
visibility = "private"
```
- Only need to allow value `private` for now.

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**
