### ISSUE TITLE
Support icon field under [package] in Ballerina.toml

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-lang#33704]
**Description:**
As the first part of https://github.com/ballerina-platform/ballerina-spec/issues/988 we should $subject in order to be able to specify an image to be used as an icon in GUI based registries.

**Syntax:**
Ballerina.toml
```toml
[package]
org = "ballerinax"
name = "app1"
version = "1.0.0"
icon = "app1.svg"
```
