### ISSUE TITLE
Changing org name in Ballerina.toml does not show any diagnostics

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#34378]
**Description:**
Consider the following Ballerina.toml config and the default module where I have added an import statement for importing the sub-module `module1`.

```toml
[package]
distribution = "slbeta6"
name="project2"
org="malintha"
version="1.0.0"
export=["project2","project2.module1"]


[build-options]
observabilityIncluded = true
```

```ballerina
import malintha/project2.module1;
import ballerina/io;


public function main() {
    io:print(module1:hello("Ballerina"));
}
```

Now, When I change the org name in ballerina toml as follows I do not get any diagnostics for the import statement. 

![baltoml](https://user-images.githubusercontent.com/35211477/146489242-5c5ad4fa-34c4-4984-aa00-d358e706bc57.png)

![main](https://user-images.githubusercontent.com/35211477/146489277-1a88af4d-f8a4-4551-a6a3-7c252ca623e1.png)

**Steps to reproduce:**
This is reproducible only when there is the `exports` array in the `package` table. 

**Affected Versions:**
slbeta6, slbeta7-snapshot
