### ISSUE TITLE
Incompatible types error for same distinct type of different versions of the same module

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#35175]
**Description:**
When loaded via the BIR, package IDs could have different versions. $title happens since the type ID check checks for exact version.

**Steps to reproduce:**
1. Build and push 1.0.0 of testorg/distinct_foo which has a distinct error.
```ballerina
public type Error distinct error;
```

2. Build and push 1.0.0 of testorg/distinct_bar that uses testorg/distinct_foo.
```ballerina
import testorg/distinct_foo;

public function fn(distinct_foo:Error e) {

}
```

3. Trigger caching the BIR for 1 and 2 via another module testorg/distinct_baz.
```ballerina
import testorg/distinct_foo as _;
import testorg/distinct_bar as _;
```

4. Push a patch version 1.0.1 of testorg/distinct_foo.

5. Use  testorg/distinct_foo 1.0.1 in source that also imports testorg/distinct_bar 1.0.0, and use the distinct error.

```toml
[[dependency]]
org = "testorg"
name = "distinct_foo"
version = "1.0.1"
repository = "local"

[[dependency]]
org = "testorg"
name = "distinct_bar"
version = "1.0.0"
repository = "local"
```

```ballerina
import testorg/distinct_foo;
import testorg/distinct_bar;

public function fn2(distinct_foo:Error e) {
    distinct_bar:fn(e);
}
```

This results in a compilation error.

**Affected Versions:**
2201.0.x
