### ISSUE TITLE
Add support to enable component model generation via Ballerina.toml

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#39584]
### Description

$subject should be done, in addition to the existing support to export the package component model via bal build command flag.

With this new support, the component model will be exported by setting up the below entry in `Ballerina.toml` file of the related package.

```toml
[build-options]
exportComponentModel = true
```

### Related area

-> Other Area
