### ISSUE TITLE
[Bug]: Program won't start with default value set for array/map/table field in configurable record

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#40277]
### Description

When a default value exists for a field of array, map, or table type in a configurable record, the Ballerina program fails to start with the following error.

```
error: {ballerina/lang.map}InherentTypeViolation {"message":"invalid value for record field 'url': expected value of type '(string[] & readonly)', found 'string[]'"}
```

### Steps to Reproduce

Here is the code snippet. 

```ballerina
type Endpoint record {|
    string basePath;
    string[] url = [];
|};

configurable Endpoint[] endpoints = [];
```

Config.toml
```toml
[[endpoints]]
basePath = "/api/entitlement-service"
url = ["https://abc.com/api/entitlement-service"]

```

### Affected Version(s)

2201.5.0

### Related area

-> Runtime
