### ISSUE TITLE
[Bug]: Toml quoted keys are not parsed properly

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#40278]
### Description

For each toml quoted key, I can see additional double quotes around it. 
```
[{"basePath":"/api/entitlement-service","url":["https://abc.com/api/entitlement-service"],"config":{""foo.bar.baz"":"value"}}]
```
Config.toml
```toml
[[endpoints]]
basePath = "/api/entitlement-service"
url = ["https://abc.com/api/entitlement-service"]
config = {"foo.bar.baz" = "value"}
```

### Steps to Reproduce

Use the below code snippet
```ballerina
type Endpoint record {|
    string basePath;
    string[] url;
    map<string> config;
|};

configurable Endpoint[] endpoints = [];
```

Config.toml
```toml
[[endpoints]]
basePath = "/api/entitlement-service"
url = ["https://abc.com/api/entitlement-service"]
config = {"foo.bar.baz" = "value"}
```

### Affected Version(s)

2201.5.0

### Related area

-> Compilation

**Comment by sameerajayasoma** [comment]
This will be a blocker pretty soon. We need this to implement service registration and discovery proposal.

**Comment by xlight05** [comment]
Had a look at this today.
From toml parsers side, As I remember, adding the quotes into quoted keys was intentional. This is due to complexities when retrieving via dotted keys. 

Consider the following sample - 
```toml
"foo.bar" = "value"

[foo]
bar = "value1"
```

Both the entries are different right? First one is a key value par in root level, and 2nd one is inside a table. But when we want to retrieve via dotted keys. we always have to use "foo.bar" for both cases. I believe that's why we made surrounding quotes required when we wanna retrieve quoted strings. This is the same behavior in parsers like Toml4j as well.


However, in `Config.toml` case this doesn't really matter. Had a chat with @HindujaB today. We'll introduce an API without quotes for the Configurables to use in the AST level.
