### ISSUE TITLE
[Bug]: bal test required to provide values to configurables which are not used in the testcases

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-lang#41792]
### Description

The Ballerina project contains the `initializeClient` function which is used to initialize MySQL client.
```ballerina
final db:Client dbClient = check initializeClient();

function initializeClient() returns db:Client|error {
   return new ();
}
```
To initialize the client, we need to set the following set of configurable,
```toml
[mock_with_h2.db]
hostname = "localhost"
port1 = 3307
username = ""
pwd = ""
db = "hospitaldb"
```

In the test cases, we try to mock the `initializeClient` and mock the MySQL client with the H2 client like below,
```
@test:Mock {functionName: "initializeClient"}
isolated function getMockClient() returns db:Client|error {
    return test:mock(db:Client, check new Client("jdbc:h2:./test", "sa", "", options = {}));         
}
```

For the H2 client, we are setting the following values in the `Config.toml` file,
```toml
url = "jdbc:h2:./test"
user = "sa"
password = ""
```

When we add only H2 client-related configuration, the `bal test` fails and asks for values for the MySQL configuration which is not used in the test cases.

### Steps to Reproduce
Project Source: https://github.com/daneshk/persist-test-samples/blob/main/mock_with_h2/tests/Config.toml

### Affected Version(s)
Ballerina Swan Lake
