### ISSUE TITLE
[New Feature]: Design new configurations for ballerina observability (automatic instrumentation)

### ISSUE THREAD

**Issue by NipunaMadhushan** [ballerina-platform/ballerina-lang#41924]
### Description

Currently, we need to configure the following to enable observability features.

`Ballerina.toml` - 
```toml
[build-options]
observabilityIncluded=true
```

`Config.toml` -
```toml
[ballerina.observe]
metricsEnabled=true
metricsReporter="prometheus"
tracingEnabled=true
tracingProvider="jaeger"
```

`bal file` - 
```php
import ballerinax/prometheus as _;
import ballerinax/jaeger as _;
```

But in terms of automatic instrumentation there should not be any module we need to import in the code level. Observability should be enabled only via configurations in automatic instrumentation. Therefore we need to change the current design of enabling observability. We need to import the `tracingProvider` or `metricsReporter` by reading the configurations. 

`observability-symbols.jar` is also generated when observability is enabled which contains `syntax-tree.json`. It was previously used by Choreo. But now they do not need the jar as they removed the observability features related to ballerina. Therefore now we should add another configuration to check whether to generate the `observability-symbols.jar` or not.

### Related area

-> Observability
