### ISSUE TITLE
[Improvement]: Allow specifying the minimum compatible version of build tools in the Ballerina.toml 

### ISSUE THREAD

**Issue by gayaldassanayake** [ballerina-platform/ballerina-lang#43089]
### Description

Currently, we can integrate build tools into a Ballerina package. The versions of the tool used to build the package is saved in the Dependencies.toml, similar to the packages.

### Describe your problem(s)

However, we don't allow specifying the minimum compatible tool version in the Ballerina.toml. This is permitted for packages, but not yet for tools.

### Describe your solution(s)

Allow specifying minimum compatible tool version in the Ballerina.toml

``` toml
[[tool-dependency]]
id = "health"	
org = "ballerina"
name = "tool_openapi"
version = "2.1.1"
```

* Note - The exact design of this needs to be finalized.

### Related area

-> Compilation
