### ISSUE TITLE
[Bug]: Enable temporary disabled github workflow-only failing `QueryExprWithQueryConstructTypeTest.testNegativeScenarios`

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-lang#43339]
### Description

$subject. 

The test was disabled with [cceeb84](https://github.com/ballerina-platform/ballerina-lang/pull/43303/commits/cceeb840695c649793c7f21b777b8d384524c5b0) in #43303 in nutcracker branch. 

The test is passing locally. However, failing in the github Ubuntu and Windows builds.

When the test is run separately with the following workflow, it gets passed in the workflow. Hence, the original failuture could be due to a conflict with the other tests. Need to investigate. 

```yaml
name: CI GITHUB FAILING TEST RUN

on:
  pull_request:
    branches:
      - nutcracker

jobs:
  run_query_expr_tests:
    name: Run QueryExprWithQueryConstructTypeTest on Ubuntu
    runs-on: ubuntu-latest
    timeout-minutes: 5
    concurrency:
      group: ${{ github.head_ref }}-ubuntu
      cancel-in-progress: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17.0.7'

      - name: Initialize sub-modules
        run: git submodule update --init

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ github.sha }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build and Run Tests
        run: ./gradlew :jballerina-unit-test:test --tests "org.ballerinalang.test.query.QueryExprWithQueryConstructTypeTest"
```

### Affected Version(s)

Nutcracker branch

### Related area

-> Compilation
