### ISSUE TITLE
[New Feature]: Log metrics for each response

### ISSUE THREAD

**Issue by NipunaMadhushan** [ballerina-platform/ballerina-lang#43614]
### Description

We need to implement log based metrics for Ballerina as a requirement for all WSO2 on-prem and SaaS products that need to use the same stack for observability. In order to retrieve metrics data using OpenSearch, we need to provide log based metrics which contain a format as follows.

[Time Stamp] protocol:<protocol_type>, tagKey1:tagValue1, tagKey2:tagValue2, .. | response_time:<value_in_seconds>

This feature is configurable in runtime and can be configured as follows in the `Config.toml` for the ballerina/observe module. By default, this configuration will be false.

```toml
[ballerina.observe]
metricsLogsEnabled=true
metricsLogsProvider="metricsLogsProvider"
```

### Related area

-> Compilation
