### ISSUE TITLE
[Improvement]: Build tools cannot be published to the local repository

### ISSUE THREAD

**Issue by gayaldassanayake** [ballerina-platform/ballerina-lang#43790]
### Description

Currently, we can publish bal tools to the local repository for testing purposes. However, we cannot do the same for build tools that are integrated with the package build. We need the local repo before we expose the feature to the general public.

### Describe your problem(s)

No support for local repo publishing for build tools

### Describe your solution(s)

Allow build tools to be used from local repo and custom repositories.

``` toml
[[tool.sample_cmd]]
id = "sample_cmd"
filePath = "sample.json"
version = "x.x.x"
repository = "local"
targetModule = "mod_sample"
options.mode = "client"
```

### Related area

-> Compilation
